apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: seongdong/nginx-test
  newName: seongdong/nginx-test
  newTag: 0.5
resources:
- ../../base
patchesStrategicMerge:
- nginx-cicd_patch.yaml
