apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: harbor.icurfer.com/library/nginx-test
  newTag: "0.14"
resources:
- ../../base
patchesStrategicMerge:
- nginx-cicd_patch.yaml
