apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicd-nginx-dp
  namespace: test
  labels:
    app: dev-nginx
spec:
  selector:
    matchLabels:
      app: cicd-nginx
  template:
    metadata:
      labels:
        app: cicd-nginx
    spec:
      containers:
      - name : nginx