apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicd-nginx-dp
  namespace: test
  labels:
    app: cicd-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cicd-nginx
  template:
    metadata:
      labels:
        app: cicd-nginx
    spec:
      containers:
      - name : cicd-nginx-con
        image: harbor.icurfer.com/library/nginx-test:0.1