apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-dp-cicd
  namespace: test
  labels:
    app: nginx-cicd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-cicd
  template:
    metadata:
      labels:
        app: nginx-cicd
    spec:
      containers:
      - name : nginx
        image: seongdong/nginx-test:0.5
---
apiVersion: v1
kind: Service
metadata:
  name: svc-cicd
  namespace: test
spec:
  selector:
    app: nginx-cicd
  ports:
  - protocol: TCP
    port: 80
#  type: NodePort
